import 'package:flutter/material.dart';
import 'package:flutterapp/dentellapp/generatedcamerawidget2/generated/GeneratedVectorWidget29.dart';
import 'package:flutterapp/dentellapp/generatedcamerawidget2/generated/GeneratedRectangle24Widget6.dart';
import 'package:flutterapp/dentellapp/generatedcamerawidget2/generated/GeneratedImage1Widget4.dart';
import 'package:flutterapp/dentellapp/generatedcamerawidget2/generated/GeneratedGroup36238Widget.dart';
import 'package:flutterapp/dentellapp/generatedcamerawidget2/generated/GeneratedGroup29Widget2.dart';
import 'package:flutterapp/dentellapp/generatedcamerawidget2/generated/GeneratedRectangle27Widget6.dart';
import 'package:flutterapp/dentellapp/generatedcamerawidget2/generated/GeneratedGroup36203Widget4.dart';
import 'package:flutterapp/dentellapp/generatedcamerawidget2/generated/GeneratedRectangle26Widget2.dart';
import 'package:flutterapp/dentellapp/generatedcamerawidget2/generated/GeneratedPexelsgriffinwooldridge26579601Widget3.dart';
import 'package:flutterapp/dentellapp/generatedcamerawidget2/generated/GeneratedGroup36239Widget.dart';
import 'package:flutterapp/dentellapp/generatedcamerawidget2/generated/GeneratedFrame3Widget.dart';

/* Frame Camera
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCameraWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -74.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 459.0,
                height: 687.0,
                child: GeneratedPexelsgriffinwooldridge26579601Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle26Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 56.0,
                child: GeneratedRectangle27Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: -121.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 783.0,
                child: GeneratedImage1Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 168.0,
                child: GeneratedRectangle24Widget6(),
              ),
              Positioned(
                left: 41.0,
                top: 708.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedGroup36238Widget(),
              ),
              Positioned(
                left: 242.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 138.0,
                child: GeneratedGroup29Widget2(),
              ),
              Positioned(
                left: 152.0,
                top: 692.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 72.0,
                child: GeneratedGroup36239Widget(),
              ),
              Positioned(
                left: 295.0,
                top: 708.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedFrame3Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 16.00008201599121,
                height: 16.0,
                child: GeneratedGroup36203Widget4(),
              ),
              Positioned(
                left: 327.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 15.99993896484375,
                height: 24.0,
                child: GeneratedVectorWidget29(),
              )
            ]),
      ),
    ));
  }
}
