import 'package:flutter/material.dart';
import 'package:flutterapp/dentellapp/generatedsignupwidget/generated/GeneratedGroup61Widget.dart';
import 'package:flutterapp/dentellapp/generatedsignupwidget/generated/GeneratedUIBarsStatusBarsWhiteBaseWidget4.dart';
import 'package:flutterapp/dentellapp/generatedsignupwidget/generated/GeneratedGroup62Widget.dart';
import 'package:flutterapp/dentellapp/generatedsignupwidget/generated/GeneratedGroup63Widget.dart';
import 'package:flutterapp/dentellapp/generatedsignupwidget/generated/GeneratedGroup65Widget2.dart';
import 'package:flutterapp/dentellapp/generatedsignupwidget/generated/GeneratedGroup33Widget1.dart';
import 'package:flutterapp/dentellapp/generatedsignupwidget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/dentellapp/generatedsignupwidget/generated/GeneratedGroup65Widget1.dart';
import 'package:flutterapp/dentellapp/generatedsignupwidget/generated/GeneratedGroup66Widget1.dart';
import 'package:flutterapp/dentellapp/generatedsignupwidget/generated/GeneratedCreateAnAccountWidget.dart';

/* Frame Signup
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 247, 169, 160),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedUIBarsStatusBarsWhiteBaseWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 673.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 139.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 224.0,
                height: 36.0,
                child: GeneratedCreateAnAccountWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 83.0,
                child: GeneratedGroup61Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 252.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 83.0,
                child: GeneratedGroup62Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 83.0,
                child: GeneratedGroup63Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 83.0,
                child: GeneratedGroup66Widget1(),
              ),
              Positioned(
                left: 102.0,
                top: 703.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 17.0,
                child: GeneratedGroup65Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 44.0,
                child: GeneratedGroup33Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 736.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 42.0,
                child: GeneratedGroup65Widget2(),
              )
            ]),
      ),
    ));
  }
}
