import 'package:flutter/material.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedConsiderseeingadoctorWidget.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedGroup36232Widget2.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedRecommendedProductsWidget.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedBread1Widget.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedOurSystemPrognosisTartarDepositPrognosisConfidence85Wid.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedImage1Widget3.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedStroke2Widget6.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedGroup36234Widget1.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedPexelsgriffinwooldridge26579602Widget.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedGroup36233Widget1.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedRectangle24Widget5.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedRectangle27Widget5.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedModeLightWidget5.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedGroup29Widget1.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedGroup36210Widget3.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedDescriptionEveryonehasdentalplaqueThisstickyfilmformson.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedRectangle32Widget1.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedRectangle28Widget2.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedUIBarsStatusBarsWhiteBaseWidget2.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedGroup36203Widget3.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedViewAllWidget.dart';
import 'package:flutterapp/dentellapp/generatedresultswidget/generated/GeneratedRectangle55Widget.dart';

/* Frame Results
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedResultsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -74.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 459.0,
                height: 687.0,
                child: GeneratedPexelsgriffinwooldridge26579602Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 152.0,
                child: GeneratedRectangle27Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: -121.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 783.0,
                child: GeneratedImage1Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedUIBarsStatusBarsWhiteBaseWidget2(),
              ),
              Positioned(
                left: 62.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 251.0,
                height: 251.0,
                child: GeneratedGroup29Widget1(),
              ),
              Positioned(
                left: 157.599853515625,
                top: 262.593017578125,
                right: null,
                bottom: null,
                width: 4.800000190734863,
                height: 4.800000190734863,
                child: GeneratedStroke2Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 34.0,
                child: GeneratedModeLightWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 741.0,
                child: GeneratedRectangle24Widget5(),
              ),
              Positioned(
                left: 33.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 25.0,
                child: GeneratedGroup36203Widget3(),
              ),
              Positioned(
                left: 1.0,
                top: 283.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 530.0,
                child: GeneratedRectangle28Widget2(),
              ),
              Positioned(
                left: 33.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 34.0,
                child: GeneratedConsiderseeingadoctorWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 33.0,
                child: GeneratedRecommendedProductsWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 170.0,
                child:
                    GeneratedOurSystemPrognosisTartarDepositPrognosisConfidence85Wid(),
              ),
              Positioned(
                left: 33.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedRectangle31Widget(),
              ),
              Positioned(
                left: 193.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedRectangle32Widget1(),
              ),
              Positioned(
                left: 273.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedRectangle30Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 706.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 72.0,
                child: GeneratedGroup36210Widget3(),
              ),
              Positioned(
                left: 45.0,
                top: 620.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBread1Widget(),
              ),
              Positioned(
                left: 291.0,
                top: 626.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 36.0,
                child: GeneratedViewAllWidget(),
              ),
              Positioned(
                left: 121.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 147.91600036621094,
                height: 177.99998474121094,
                child: GeneratedGroup36234Widget1(),
              ),
              Positioned(
                left: 55.0,
                top: 662.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 43.000022888183594,
                child: GeneratedGroup36233Widget1(),
              ),
              Positioned(
                left: 215.0,
                top: 660.2574462890625,
                right: null,
                bottom: null,
                width: 25.0,
                height: 36.257442474365234,
                child: GeneratedGroup36232Widget2(),
              ),
              Positioned(
                left: 175.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 180.0,
                child: GeneratedRectangle55Widget(),
              ),
              Positioned(
                left: 188.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 153.0,
                child:
                    GeneratedDescriptionEveryonehasdentalplaqueThisstickyfilmformson(),
              )
            ]),
      ),
    ));
  }
}
