import 'package:flutter/material.dart';
import 'package:flutterapp/dentellapp/generatedsplashwidget/generated/GeneratedNUTSHELLWidget.dart';
import 'package:flutterapp/dentellapp/generatedsplashwidget/generated/Generated66761Widget.dart';
import 'package:flutterapp/dentellapp/generatedsplashwidget/generated/GeneratedModeLightWidget10.dart';
import 'package:flutterapp/dentellapp/generatedsplashwidget/generated/GeneratedAppBarTopWidget4.dart';
import 'package:flutterapp/dentellapp/generatedsplashwidget/generated/GeneratedDentellWidget3.dart';

/* Frame Splash
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedWelcome1Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 247, 169, 160),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 778.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 34.0,
                  child: GeneratedModeLightWidget10(),
                ),
                Positioned(
                  left: 0.0,
                  top: 8.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 44.0,
                  child: GeneratedAppBarTopWidget4(),
                ),
                Positioned(
                  left: 122.0,
                  top: 697.0,
                  right: null,
                  bottom: null,
                  width: 136.0,
                  height: 25.0,
                  child: GeneratedNUTSHELLWidget(),
                ),
                Positioned(
                  left: 55.0,
                  top: 357.0,
                  right: null,
                  bottom: null,
                  width: 281.0,
                  height: 104.0,
                  child: GeneratedDentellWidget3(),
                ),
                Positioned(
                  left: -2051.0,
                  top: -797.0,
                  right: null,
                  bottom: null,
                  width: 4533.33349609375,
                  height: 2666.666748046875,
                  child: Generated66761Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
