import 'package:flutter/material.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedMaskGroupWidget1.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedPexelsgriffinwooldridge26579601Widget2.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedNavigation1Widget1.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedGroup25Widget1.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedGroup36232Widget1.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedGroup27Widget1.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedRectangle27Widget2.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedGroup36210Widget2.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedStroke2Widget4.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedGroup36203Widget2.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedListmenu1Widget1.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedUIBarsStatusBarsWhiteBaseWidget1.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedImage1Widget2.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedModeLightWidget4.dart';
import 'package:flutterapp/dentellapp/generateddentists2widget/generated/GeneratedGroup36242Widget.dart';

/* Frame Dentists 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDentists2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -74.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 459.0,
                height: 687.0,
                child: GeneratedPexelsgriffinwooldridge26579601Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 152.0,
                child: GeneratedRectangle27Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: -121.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 783.0,
                child: GeneratedImage1Widget2(),
              ),
              Positioned(
                left: 157.599853515625,
                top: 262.593017578125,
                right: null,
                bottom: null,
                width: 4.800000190734863,
                height: 4.800000190734863,
                child: GeneratedStroke2Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 34.0,
                child: GeneratedModeLightWidget4(),
              ),
              Positioned(
                left: 28.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 16.00008201599121,
                height: 18.039840698242188,
                child: GeneratedGroup36203Widget2(),
              ),
              Positioned(
                left: 43.0,
                top: 687.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 72.0,
                child: GeneratedGroup36210Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 708.0,
                child: GeneratedMaskGroupWidget1(),
              ),
              Positioned(
                left: 285.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: GeneratedGroup36232Widget1(),
              ),
              Positioned(
                left: 132.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 24.0,
                child: GeneratedGroup25Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedUIBarsStatusBarsWhiteBaseWidget1(),
              ),
              Positioned(
                left: 21.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 42.0,
                child: GeneratedGroup27Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedNavigation1Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedListmenu1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 414.0,
                child: GeneratedGroup36242Widget(),
              )
            ]),
      ),
    ));
  }
}
