import 'package:flutter/material.dart';
import 'package:flutterapp/dentellapp/generatedpremiumwidget/generated/GeneratedMonthlyWidget.dart';
import 'package:flutterapp/dentellapp/generatedpremiumwidget/generated/GeneratedIconlyBoldHeartWidget.dart';
import 'package:flutterapp/dentellapp/generatedpremiumwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/dentellapp/generatedpremiumwidget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/dentellapp/generatedpremiumwidget/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/dentellapp/generatedpremiumwidget/generated/GeneratedGroup36250Widget.dart';
import 'package:flutterapp/dentellapp/generatedpremiumwidget/generated/GeneratedStatusBarWidget1.dart';
import 'package:flutterapp/dentellapp/generatedpremiumwidget/generated/GeneratedGroup36237Widget.dart';
import 'package:flutterapp/dentellapp/generatedpremiumwidget/generated/GeneratedWeeklyWidget.dart';
import 'package:flutterapp/dentellapp/generatedpremiumwidget/generated/GeneratedGetlongtermtrackingfreeconsultationsandothermemberexclu.dart';
import 'package:flutterapp/dentellapp/generatedpremiumwidget/generated/GeneratedModeLightWidget1.dart';
import 'package:flutterapp/dentellapp/generatedpremiumwidget/generated/GeneratedUnlockPremiumFeatureWidget.dart';
import 'package:flutterapp/dentellapp/generatedpremiumwidget/generated/GeneratedIconlyLightHomeWidget1.dart';
import 'package:flutterapp/dentellapp/generatedpremiumwidget/generated/GeneratedGetNowWidget.dart';

/* Frame Premium
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPremiumWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 34.0,
                child: GeneratedModeLightWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 105.0,
                child: GeneratedStatusBarWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 48.0,
                child: GeneratedRectangle33Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 48.0,
                child: GeneratedRectangle34Widget(),
              ),
              Positioned(
                left: 82.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 21.0,
                child: GeneratedMonthlyWidget(),
              ),
              Positioned(
                left: 242.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 21.0,
                child: GeneratedWeeklyWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 452.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 70.0,
                child:
                    GeneratedGetlongtermtrackingfreeconsultationsandothermemberexclu(),
              ),
              Positioned(
                left: 1.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 33.0,
                child: GeneratedUnlockPremiumFeatureWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 72.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 33.0,
                child: GeneratedGetNowWidget(),
              ),
              Positioned(
                left: 159.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedGroup36237Widget(),
              ),
              Positioned(
                left: 99.0,
                top: 732.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 48.0,
                child: GeneratedGroup36250Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedIconlyLightHomeWidget1(),
              ),
              Positioned(
                left: 254.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedIconlyBoldHeartWidget(),
              )
            ]),
      ),
    ));
  }
}
