import 'package:flutter/material.dart';
import 'package:flutterapp/dentellapp/generatedinstructionswidget/generated/GeneratedModeLightWidget2.dart';
import 'package:flutterapp/dentellapp/generatedinstructionswidget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/dentellapp/generatedinstructionswidget/generated/GeneratedTakephotoinawelllitenvironmentUseamirrortotracktheimage.dart';
import 'package:flutterapp/dentellapp/generatedinstructionswidget/generated/GeneratedInstructionsWidget1.dart';
import 'package:flutterapp/dentellapp/generatedinstructionswidget/generated/GeneratedGroup36203Widget.dart';
import 'package:flutterapp/dentellapp/generatedinstructionswidget/generated/GeneratedRectangle54Widget.dart';
import 'package:flutterapp/dentellapp/generatedinstructionswidget/generated/GeneratedGroup36210Widget.dart';
import 'package:flutterapp/dentellapp/generatedinstructionswidget/generated/GeneratedStroke2Widget.dart';
import 'package:flutterapp/dentellapp/generatedinstructionswidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/dentellapp/generatedinstructionswidget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/dentellapp/generatedinstructionswidget/generated/GeneratedPexelsgriffinwooldridge26579601Widget.dart';
import 'package:flutterapp/dentellapp/generatedinstructionswidget/generated/GeneratedRectangle24Widget.dart';

/* Frame Instructions
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInstructionsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -74.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 459.0,
                height: 687.0,
                child: GeneratedPexelsgriffinwooldridge26579601Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 56.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 0.0,
                top: -121.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 783.0,
                child: GeneratedImage1Widget(),
              ),
              Positioned(
                left: 157.599853515625,
                top: 262.593017578125,
                right: null,
                bottom: null,
                width: 4.800000190734863,
                height: 4.800000190734863,
                child: GeneratedStroke2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 34.0,
                child: GeneratedModeLightWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 712.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 16.00008201599121,
                height: 18.039840698242188,
                child: GeneratedGroup36203Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 36.0,
                child: GeneratedInstructionsWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 137.0,
                child:
                    GeneratedTakephotoinawelllitenvironmentUseamirrortotracktheimage(),
              ),
              Positioned(
                left: 29.000024795532227,
                top: 706.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 72.0,
                child: GeneratedGroup36210Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 178.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 238.0,
                child: GeneratedRectangle54Widget(),
              )
            ]),
      ),
    ));
  }
}
