import 'package:flutter/material.dart';
import 'package:flutterapp/dentellapp/generatedwelcome1widget/generated/GeneratedRectangle6Widget3.dart';
import 'package:flutterapp/dentellapp/generatedwelcome1widget/generated/GeneratedMaintaininggoodoralhealthshouldbetheprimaryfocusofevery.dart';
import 'package:flutterapp/dentellapp/generatedwelcome1widget/generated/GeneratedAlreadyHaveAnAcountLogInWidget1.dart';
import 'package:flutterapp/dentellapp/generatedwelcome1widget/generated/GeneratedRectangle5Widget2.dart';
import 'package:flutterapp/dentellapp/generatedwelcome1widget/generated/GeneratedModeLightWidget8.dart';
import 'package:flutterapp/dentellapp/generatedwelcome1widget/generated/GeneratedGroup36208Widget1.dart';
import 'package:flutterapp/dentellapp/generatedwelcome1widget/generated/GeneratedHealthyTeethWidget.dart';
import 'package:flutterapp/dentellapp/generatedwelcome1widget/generated/GeneratedAppBarTopWidget2.dart';
import 'package:flutterapp/dentellapp/generatedwelcome1widget/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/dentellapp/generatedwelcome1widget/generated/GeneratedDentellWidget1.dart';
import 'package:flutterapp/dentellapp/generatedwelcome1widget/generated/GeneratedGroup36232Widget4.dart';

/* Frame Welcome 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcome1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 42.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 72.0,
                child: GeneratedGroup36208Widget1(),
              ),
              Positioned(
                left: 73.0,
                top: 727.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 23.0,
                child: GeneratedAlreadyHaveAnAcountLogInWidget1(),
              ),
              Positioned(
                left: 115.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 37.0,
                child: GeneratedHealthyTeethWidget(),
              ),
              Positioned(
                left: 51.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 50.0,
                child:
                    GeneratedMaintaininggoodoralhealthshouldbetheprimaryfocusofevery(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedAppBarTopWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 34.0,
                child: GeneratedModeLightWidget8(),
              ),
              Positioned(
                left: 62.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 39.0,
                child: GeneratedDentellWidget1(),
              ),
              Positioned(
                left: 50.0,
                top: 161.58697509765625,
                right: null,
                bottom: null,
                width: 282.0,
                height: 280.41302490234375,
                child: GeneratedGroup36232Widget4(),
              ),
              Positioned(
                left: 162.0,
                top: 587.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 10.0,
                child: GeneratedRectangle5Widget2(),
              ),
              Positioned(
                left: 186.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 8.0,
                child: GeneratedRectangle6Widget3(),
              ),
              Positioned(
                left: 202.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 8.0,
                child: GeneratedRectangle7Widget1(),
              )
            ]),
      ),
    ));
  }
}
