import 'package:flutter/material.dart';
import 'package:flutterapp/dentellapp/generatedwelcome2widget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/dentellapp/generatedwelcome2widget/generated/GeneratedAppBarTopWidget3.dart';
import 'package:flutterapp/dentellapp/generatedwelcome2widget/generated/GeneratedGroup25Widget2.dart';
import 'package:flutterapp/dentellapp/generatedwelcome2widget/generated/GeneratedDentellWidget2.dart';
import 'package:flutterapp/dentellapp/generatedwelcome2widget/generated/GeneratedAtHomeCheckupsWidget.dart';
import 'package:flutterapp/dentellapp/generatedwelcome2widget/generated/GeneratedModeLightWidget9.dart';
import 'package:flutterapp/dentellapp/generatedwelcome2widget/generated/GeneratedGetStartedWidget2.dart';
import 'package:flutterapp/dentellapp/generatedwelcome2widget/generated/GeneratedRectangle1Widget9.dart';
import 'package:flutterapp/dentellapp/generatedwelcome2widget/generated/GeneratedAlreadyHaveAnAcountLogInWidget2.dart';
import 'package:flutterapp/dentellapp/generatedwelcome2widget/generated/GeneratedCheckyourteethandgumsforthemostcommondiseasesWidget.dart';

/* Frame Welcome 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcome2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 42.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 72.0,
                child: GeneratedRectangle1Widget9(),
              ),
              Positioned(
                left: 119.0,
                top: 660.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 33.0,
                child: GeneratedGetStartedWidget2(),
              ),
              Positioned(
                left: 73.0,
                top: 727.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 23.0,
                child: GeneratedAlreadyHaveAnAcountLogInWidget2(),
              ),
              Positioned(
                left: 88.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 37.0,
                child: GeneratedAtHomeCheckupsWidget(),
              ),
              Positioned(
                left: 51.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 50.0,
                child:
                    GeneratedCheckyourteethandgumsforthemostcommondiseasesWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedAppBarTopWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 34.0,
                child: GeneratedModeLightWidget9(),
              ),
              Positioned(
                left: 62.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 39.0,
                child: GeneratedDentellWidget2(),
              ),
              Positioned(
                left: 166.0,
                top: 587.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 10.0,
                child: GeneratedGroup25Widget2(),
              ),
              Positioned(
                left: 51.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 218.0,
                child: GeneratedGroup1Widget(),
              )
            ]),
      ),
    ));
  }
}
