import 'package:flutter/material.dart';
import 'package:flutterapp/dentellapp/generatedloginwidget1/generated/GeneratedGroup122Widget.dart';
import 'package:flutterapp/dentellapp/generatedloginwidget1/generated/GeneratedGroup121Widget.dart';
import 'package:flutterapp/dentellapp/generatedloginwidget1/generated/GeneratedGroup63Widget1.dart';
import 'package:flutterapp/dentellapp/generatedloginwidget1/generated/GeneratedRectangle21Widget1.dart';
import 'package:flutterapp/dentellapp/generatedloginwidget1/generated/GeneratedOrWidget.dart';
import 'package:flutterapp/dentellapp/generatedloginwidget1/generated/GeneratedGroup33Widget2.dart';
import 'package:flutterapp/dentellapp/generatedloginwidget1/generated/GeneratedUIBarsStatusBarsWhiteBaseWidget5.dart';
import 'package:flutterapp/dentellapp/generatedloginwidget1/generated/GeneratedForgotPasswordWidget.dart';
import 'package:flutterapp/dentellapp/generatedloginwidget1/generated/GeneratedGroup65Widget3.dart';
import 'package:flutterapp/dentellapp/generatedloginwidget1/generated/GeneratedGroup61Widget1.dart';
import 'package:flutterapp/dentellapp/generatedloginwidget1/generated/GeneratedWelcometoDentellWidget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedSignupWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 247, 169, 160),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 44.0,
                  child: GeneratedUIBarsStatusBarsWhiteBaseWidget5(),
                ),
                Positioned(
                  left: 20.0,
                  top: 73.0,
                  right: null,
                  bottom: null,
                  width: 243.0,
                  height: 36.0,
                  child: GeneratedWelcometoDentellWidget(),
                ),
                Positioned(
                  left: 20.0,
                  top: 140.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 83.0,
                  child: GeneratedGroup61Widget1(),
                ),
                Positioned(
                  left: 20.0,
                  top: 252.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 83.0,
                  child: GeneratedGroup63Widget1(),
                ),
                Positioned(
                  left: 20.0,
                  top: 375.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 44.0,
                  child: GeneratedGroup33Widget2(),
                ),
                Positioned(
                  left: 0.0,
                  top: 523.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 289.0,
                  child: GeneratedRectangle21Widget1(),
                ),
                Positioned(
                  left: 21.0,
                  top: 556.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 79.0,
                  child: GeneratedGroup65Widget3(),
                ),
                Positioned(
                  left: 0.0,
                  top: 431.0,
                  right: null,
                  bottom: null,
                  width: 377.0,
                  height: 16.0,
                  child: GeneratedForgotPasswordWidget(),
                ),
                Positioned(
                  left: 175.0,
                  top: 652.0,
                  right: null,
                  bottom: null,
                  width: 23.0,
                  height: 22.0,
                  child: GeneratedOrWidget(),
                ),
                Positioned(
                  left: 80.0,
                  top: 689.0,
                  right: null,
                  bottom: null,
                  width: 215.0,
                  height: 36.0,
                  child: GeneratedGroup121Widget(),
                ),
                Positioned(
                  left: 80.0,
                  top: 746.0,
                  right: null,
                  bottom: null,
                  width: 215.0,
                  height: 36.0,
                  child: GeneratedGroup122Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
