import 'package:flutter/material.dart';
import 'package:flutterapp/dentellapp/generatedhomewidget4/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/dentellapp/generatedhomewidget4/generated/GeneratedGroup36246Widget.dart';
import 'package:flutterapp/dentellapp/generatedhomewidget4/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/dentellapp/generatedhomewidget4/generated/GeneratedModeLightWidget6.dart';
import 'package:flutterapp/dentellapp/generatedhomewidget4/generated/GeneratedGroup36231Widget.dart';
import 'package:flutterapp/dentellapp/generatedhomewidget4/generated/GeneratedGroup36249Widget.dart';
import 'package:flutterapp/dentellapp/generatedhomewidget4/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/dentellapp/generatedhomewidget4/generated/GeneratedRecommendedProductsWidget1.dart';
import 'package:flutterapp/dentellapp/generatedhomewidget4/generated/GeneratedHelloPeterTakecontrolofyouroralhealthWidget.dart';
import 'package:flutterapp/dentellapp/generatedhomewidget4/generated/GeneratedAppBarTopWidget.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Container(
              width: 627.0,
              child: Stack(children: [
                Container(
                    height: constraints.maxHeight,
                    child: Container(
                      width: 375.0,
                      height: 812.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 778.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 34.0,
                              child: GeneratedModeLightWidget6(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 535.0,
                              right: null,
                              bottom: null,
                              width: 603.0,
                              height: 174.0,
                              child: GeneratedGroup36246Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 732.0,
                              right: null,
                              bottom: null,
                              width: 328.0,
                              height: 48.0,
                              child: GeneratedGroup36249Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 8.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 44.0,
                              child: GeneratedAppBarTopWidget(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 173.0,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 169.0,
                              child: GeneratedGroup19Widget(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 310.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 106.0,
                              child: GeneratedGroup36231Widget(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 352.0,
                              right: null,
                              bottom: null,
                              width: 52.0,
                              height: 10.0,
                              child: GeneratedGroup20Widget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 98.0,
                              right: null,
                              bottom: null,
                              width: 238.0,
                              height: 61.0,
                              child:
                                  GeneratedHelloPeterTakecontrolofyouroralhealthWidget(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 376.0,
                              right: null,
                              bottom: null,
                              width: 321.0,
                              height: 90.0,
                              child: GeneratedGroup18Widget(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 490.0,
                              right: null,
                              bottom: null,
                              width: 223.0,
                              height: 22.0,
                              child: GeneratedRecommendedProductsWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
