import 'package:flutter/material.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedPeterWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedGroup36251Widget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedRectangle51Widget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedUpgradetoPremiumWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedModeLightWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedIconlyBoldProfileWidget2.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedBasicMememberWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedIconlyBoldProfileWidget1.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedIconlyLightArrowRight5Widget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedIconlyLightSearchWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedIconlyLightHeartWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedIconlyBoldProfileWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedIconlyLightArrowRight3Widget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedStatusBarWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedSettingsWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedIconlyLightArrowRight2Widget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedIconlyBoldPaperWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedBarsStatusBariPhoneLightWidget1.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedRectangle50Widget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedIconlyBoldSettingWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedIconlyLightHomeWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedTermsPrivacyPolicyWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedIconlyBoldCameraWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedRectangle52Widget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedRectangle44Widget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedIconlyLightArrowRight4Widget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedIconlyBoldStarWidget.dart';
import 'package:flutterapp/dentellapp/generatedprofilewidget/generated/GeneratedEditProfileWidget.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 123.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 164.0,
                top: 732.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 48.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 176.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIconlyBoldCameraWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedIconlyLightHomeWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 34.0,
                child: GeneratedModeLightWidget(),
              ),
              Positioned(
                left: 100.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedIconlyLightSearchWidget(),
              ),
              Positioned(
                left: 248.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedIconlyLightHeartWidget(),
              ),
              Positioned(
                left: 320.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedIconlyBoldProfileWidget(),
              ),
              Positioned(
                left: 143.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 90.0,
                child: GeneratedIconlyBoldProfileWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 105.0,
                child: GeneratedStatusBarWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedBarsStatusBariPhoneLightWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 29.0,
                child: GeneratedPeterWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 22.0,
                child: GeneratedBasicMememberWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 48.0,
                child: GeneratedRectangle52Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 48.0,
                child: GeneratedRectangle44Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedIconlyBoldProfileWidget2(),
              ),
              Positioned(
                left: 32.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 48.0,
                child: GeneratedRectangle50Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 48.0,
                child: GeneratedRectangle51Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedIconlyBoldSettingWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedIconlyBoldPaperWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 28.0,
                child: GeneratedIconlyBoldStarWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 23.0,
                child: GeneratedEditProfileWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 23.0,
                child: GeneratedUpgradetoPremiumWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 26.0,
                child: GeneratedSettingsWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 23.0,
                child: GeneratedTermsPrivacyPolicyWidget(),
              ),
              Positioned(
                left: 319.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIconlyLightArrowRight2Widget(),
              ),
              Positioned(
                left: 319.0,
                top: 452.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIconlyLightArrowRight3Widget(),
              ),
              Positioned(
                left: 319.0,
                top: 516.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIconlyLightArrowRight4Widget(),
              ),
              Positioned(
                left: 319.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIconlyLightArrowRight5Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 48.0,
                child: GeneratedGroup36251Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 1.0,
                child: GeneratedLine5Widget(),
              )
            ]),
      ),
    ));
  }
}
