import 'package:flutter/material.dart';
import 'package:flutterapp/dentellapp/generatedwelcome3widget/generated/GeneratedTrackYourHealthWidget.dart';
import 'package:flutterapp/dentellapp/generatedwelcome3widget/generated/GeneratedMobilecuate1Widget.dart';
import 'package:flutterapp/dentellapp/generatedwelcome3widget/generated/GeneratedModeLightWidget7.dart';
import 'package:flutterapp/dentellapp/generatedwelcome3widget/generated/GeneratedAlreadyHaveAnAcountLogInWidget.dart';
import 'package:flutterapp/dentellapp/generatedwelcome3widget/generated/GeneratedGroup36208Widget.dart';
import 'package:flutterapp/dentellapp/generatedwelcome3widget/generated/GeneratedDentellWidget.dart';
import 'package:flutterapp/dentellapp/generatedwelcome3widget/generated/GeneratedAppBarTopWidget1.dart';
import 'package:flutterapp/dentellapp/generatedwelcome3widget/generated/GeneratedWithamazinginbuilttoolsyoucantrackyourprogressWidget.dart';
import 'package:flutterapp/dentellapp/generatedwelcome3widget/generated/GeneratedGroup23Widget.dart';

/* Frame Welcome 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcome3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 42.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 72.0,
                child: GeneratedGroup36208Widget(),
              ),
              Positioned(
                left: 73.0,
                top: 727.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 23.0,
                child: GeneratedAlreadyHaveAnAcountLogInWidget(),
              ),
              Positioned(
                left: 95.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 37.0,
                child: GeneratedTrackYourHealthWidget(),
              ),
              Positioned(
                left: 51.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 50.0,
                child:
                    GeneratedWithamazinginbuilttoolsyoucantrackyourprogressWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedAppBarTopWidget1(),
              ),
              Positioned(
                left: 162.0,
                top: 587.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 10.0,
                child: GeneratedGroup23Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 178.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 282.0,
                child: GeneratedMobilecuate1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 34.0,
                child: GeneratedModeLightWidget7(),
              ),
              Positioned(
                left: 62.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 39.0,
                child: GeneratedDentellWidget(),
              )
            ]),
      ),
    ));
  }
}
