import 'package:flutter/material.dart';
import 'package:flutterapp/dentellapp/generatedconfirmationwidget/generated/GeneratedMultiply1Widget.dart';
import 'package:flutterapp/dentellapp/generatedconfirmationwidget/generated/GeneratedUndraw_begin_chat_c6pj1Widget.dart';
import 'package:flutterapp/dentellapp/generatedconfirmationwidget/generated/GeneratedUIBarsStatusBarsWhiteBaseWidget3.dart';
import 'package:flutterapp/dentellapp/generatedconfirmationwidget/generated/GeneratedThankYouForYourConfirmationWidget.dart';

/* Frame Confirmation
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedConfirmationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 247, 169, 160),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedUIBarsStatusBarsWhiteBaseWidget3(),
              ),
              Positioned(
                left: 331.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMultiply1Widget(),
              ),
              Positioned(
                left: 44.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 207.0,
                child: GeneratedUndraw_begin_chat_c6pj1Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 70.0,
                child: GeneratedThankYouForYourConfirmationWidget(),
              )
            ]),
      ),
    ));
  }
}
